import { Dimensions } from 'react-native';

const SIZES = {
  IMAGE_HEIGHT: 300,
  IMAGE_WIDTH: '80%',
  MIN_IMAGE_WIDTH: Dimensions.get('screen').width - 120,
  BUBBLE_CHAT_MAX_WIDTH: Dimensions.get('screen').width - 120,
  BUBBLE_CHAT_PADDING: 10,
  BUBBLE_CHAT_MARGIN_HORIZONTAL: 5,
  BUBBLE_CHAT_MARGIN_VERTICAL: 15,
  BUBBLE_CHAT_GAP: 5,
  BUBBLE_CHAT_LINE_HEIGHT: 20,
  BUBBLE_CHAT_FOOTER_HEIGHT: 15,
  BUBBLE_CHAT_REPLIED_MESSAGE_MAX_HEIGHT: 75,
  BUBBLE_CHAT_REPLIED_MESSAGE_PADDING: 5,
  BUBBLE_CHAT_REPLIED_MESSAGE_MARGIN_BOTTOM: 5,
};

export default SIZES;
