import { Registry } from '../registry/schema'

const example: Registry = [
  {
    name: 'accordion-demo',
    type: 'components:example',
    registryDependencies: ['accordion'],
    files: ['src/docs/components/example/accordion-demo.tsx'],
  },
  {
    name: 'alert-demo',
    type: 'components:example',
    registryDependencies: ['alert'],
    files: ['src/docs/components/example/alert-demo.tsx'],
  },
  {
    name: 'alert-destructive',
    type: 'components:example',
    registryDependencies: ['alert'],
    files: ['src/docs/components/example/alert-destructive.tsx'],
  },
  {
    name: 'alert-dialog-demo',
    type: 'components:example',
    registryDependencies: ['alert-dialog', 'button'],
    files: ['src/docs/components/example/alert-dialog-demo.tsx'],
  },
  {
    name: 'avatar-demo',
    type: 'components:example',
    registryDependencies: ['avatar'],
    files: ['src/docs/components/example/avatar-demo.tsx'],
  },
  {
    name: 'badge-demo',
    type: 'components:example',
    registryDependencies: ['badge'],
    files: ['src/docs/components/example/badge-demo.tsx'],
  },
  {
    name: 'badge-destructive',
    type: 'components:example',
    registryDependencies: ['badge'],
    files: ['src/docs/components/example/badge-destructive.tsx'],
  },
  {
    name: 'badge-outline',
    type: 'components:example',
    registryDependencies: ['badge'],
    files: ['src/docs/components/example/badge-outline.tsx'],
  },
  {
    name: 'badge-secondary',
    type: 'components:example',
    registryDependencies: ['badge'],
    files: ['src/docs/components/example/badge-secondary.tsx'],
  },
  {
    name: 'button-demo',
    type: 'components:example',
    registryDependencies: ['button'],
    files: ['src/docs/components/example/button-demo.tsx'],
  },
  {
    name: 'button-secondary',
    type: 'components:example',
    registryDependencies: ['button'],
    files: ['src/docs/components/example/button-secondary.tsx'],
  },
  {
    name: 'button-destructive',
    type: 'components:example',
    registryDependencies: ['button'],
    files: ['src/docs/components/example/button-destructive.tsx'],
  },
  {
    name: 'button-outline',
    type: 'components:example',
    registryDependencies: ['button'],
    files: ['src/docs/components/example/button-outline.tsx'],
  },
  {
    name: 'button-ghost',
    type: 'components:example',
    registryDependencies: ['button'],
    files: ['src/docs/components/example/button-ghost.tsx'],
  },
  {
    name: 'button-link',
    type: 'components:example',
    registryDependencies: ['button'],
    files: ['src/docs/components/example/button-link.tsx'],
  },
  {
    name: 'button-with-icon',
    type: 'components:example',
    registryDependencies: ['button'],
    files: ['src/docs/components/example/button-with-icon.tsx'],
  },
  {
    name: 'button-loading',
    type: 'components:example',
    registryDependencies: ['button'],
    files: ['src/docs/components/example/button-loading.tsx'],
  },
  {
    name: 'button-icon',
    type: 'components:example',
    registryDependencies: ['button'],
    files: ['src/docs/components/example/button-icon.tsx'],
  },
  {
    name: 'button-as-child',
    type: 'components:example',
    registryDependencies: ['button'],
    files: ['src/docs/components/example/button-as-child.tsx'],
  },
  // {
  //   name: 'calendar-demo',
  //   type: 'components:example',
  //   registryDependencies: ['calendar'],
  //   files: ['src/docs/components/example/calendar-demo.tsx'],
  // },
  // {
  //   name: 'calendar-form',
  //   type: 'components:example',
  //   registryDependencies: ['calendar', 'form', 'popover'],
  //   files: ['src/docs/components/example/calendar-form.tsx'],
  // },
  {
    name: 'card-demo',
    type: 'components:example',
    registryDependencies: ['card', 'button', 'switch'],
    files: ['src/docs/components/example/card-demo.tsx'],
  },
  {
    name: 'card-with-form',
    type: 'components:example',
    registryDependencies: ['button', 'card', 'input', 'label', 'select'],
    files: ['src/docs/components/example/card-with-form.tsx'],
  },
  {
    name: 'carousel-demo',
    type: 'components:example',
    registryDependencies: ['carousel'],
    files: ['src/docs/components/example/carousel-demo.tsx'],
  },
  {
    name: 'carousel-size',
    type: 'components:example',
    registryDependencies: ['carousel'],
    files: ['src/docs/components/example/carousel-size.tsx'],
  },
  {
    name: 'carousel-spacing',
    type: 'components:example',
    registryDependencies: ['carousel'],
    files: ['src/docs/components/example/carousel-spacing.tsx'],
  },
  {
    name: 'carousel-orientation',
    type: 'components:example',
    registryDependencies: ['carousel'],
    files: ['src/docs/components/example/carousel-orientation.tsx'],
  },
  {
    name: 'carousel-api',
    type: 'components:example',
    registryDependencies: ['carousel'],
    files: ['src/docs/components/example/carousel-api.tsx'],
  },
  {
    name: 'carousel-plugin',
    type: 'components:example',
    registryDependencies: ['carousel'],
    files: ['src/docs/components/example/carousel-plugin.tsx'],
  },
  {
    name: 'checkbox-demo',
    type: 'components:example',
    registryDependencies: ['checkbox'],
    files: ['src/docs/components/example/checkbox-demo.tsx'],
  },
  {
    name: 'checkbox-disabled',
    type: 'components:example',
    registryDependencies: ['checkbox'],
    files: ['src/docs/components/example/checkbox-disabled.tsx'],
  },
  // {
  //   name: 'checkbox-form-multiple',
  //   type: 'components:example',
  //   registryDependencies: ['checkbox', 'form'],
  //   files: ['src/docs/components/example/checkbox-form-multiple.tsx'],
  // },
  // {
  //   name: 'checkbox-form-single',
  //   type: 'components:example',
  //   registryDependencies: ['checkbox', 'form'],
  //   files: ['src/docs/components/example/checkbox-form-single.tsx'],
  // },
  // {
  //   name: 'checkbox-with-text',
  //   type: 'components:example',
  //   registryDependencies: ['checkbox'],
  //   files: ['src/docs/components/example/checkbox-with-text.tsx'],
  // },
  // {
  //   name: 'collapsible-demo',
  //   type: 'components:example',
  //   registryDependencies: ['collapsible'],
  //   files: ['src/docs/components/example/collapsible-demo.tsx'],
  // },
  // {
  //   name: 'combobox-demo',
  //   type: 'components:example',
  //   registryDependencies: ['command'],
  //   files: ['src/docs/components/example/combobox-demo.tsx'],
  // },
  // {
  //   name: 'combobox-dropdown-menu',
  //   type: 'components:example',
  //   registryDependencies: ['command', 'dropdown-menu', 'button'],
  //   files: ['src/docs/components/example/combobox-dropdown-menu.tsx'],
  // },
  // {
  //   name: 'combobox-form',
  //   type: 'components:example',
  //   registryDependencies: ['command', 'form'],
  //   files: ['src/docs/components/example/combobox-form.tsx'],
  // },
  // {
  //   name: 'combobox-popover',
  //   type: 'components:example',
  //   registryDependencies: ['combobox', 'popover'],
  //   files: ['src/docs/components/example/combobox-popover.tsx'],
  // },
  // {
  //   name: 'combobox-responsive',
  //   type: 'components:example',
  //   registryDependencies: ['combobox', 'popover', 'drawer'],
  //   files: ['src/docs/components/example/combobox-responsive.tsx'],
  // },
  // {
  //   name: 'command-demo',
  //   type: 'components:example',
  //   registryDependencies: ['command'],
  //   files: ['src/docs/components/example/command-demo.tsx'],
  // },
  // {
  //   name: 'command-dialog',
  //   type: 'components:example',
  //   registryDependencies: ['command', 'dialog'],
  //   files: ['src/docs/components/example/command-dialog.tsx'],
  // },
  // {
  //   name: 'context-menu-demo',
  //   type: 'components:example',
  //   registryDependencies: ['context-menu'],
  //   files: ['src/docs/components/example/context-menu-demo.tsx'],
  // },
  // {
  //   name: 'data-table-demo',
  //   type: 'components:example',
  //   registryDependencies: ['data-table'],
  //   files: ['src/docs/components/example/data-table-demo.tsx'],
  // },
  // {
  //   name: 'date-picker-demo',
  //   type: 'components:example',
  //   registryDependencies: ['button', 'calendar', 'popover'],
  //   files: ['src/docs/components/example/date-picker-demo.tsx'],
  //   dependencies: ['date-fns'],
  // },
  // {
  //   name: 'date-picker-form',
  //   type: 'components:example',
  //   registryDependencies: ['button', 'calendar', 'form', 'popover'],
  //   files: ['src/docs/components/example/date-picker-form.tsx'],
  //   dependencies: ['date-fns'],
  // },
  // {
  //   name: 'date-picker-with-presets',
  //   type: 'components:example',
  //   registryDependencies: ['button', 'calendar', 'popover', 'select'],
  //   files: ['src/docs/components/example/date-picker-with-presets.tsx'],
  //   dependencies: ['date-fns'],
  // },
  // {
  //   name: 'date-picker-with-range',
  //   type: 'components:example',
  //   registryDependencies: ['button', 'calendar', 'popover'],
  //   files: ['src/docs/components/example/date-picker-with-range.tsx'],
  //   dependencies: ['date-fns'],
  // },
  // {
  //   name: 'dialog-demo',
  //   type: 'components:example',
  //   registryDependencies: ['dialog'],
  //   files: ['src/docs/components/example/dialog-demo.tsx'],
  // },
  // {
  //   name: 'dialog-close-button',
  //   type: 'components:example',
  //   registryDependencies: ['dialog', 'button'],
  //   files: ['src/docs/components/example/dialog-close-button.tsx'],
  // },
  // {
  //   name: 'drawer-demo',
  //   type: 'components:example',
  //   registryDependencies: ['drawer'],
  //   files: ['src/docs/components/example/drawer-demo.tsx'],
  // },
  // {
  //   name: 'drawer-dialog',
  //   type: 'components:example',
  //   registryDependencies: ['drawer', 'dialog'],
  //   files: ['src/docs/components/example/drawer-dialog.tsx'],
  // },
  // {
  //   name: 'dropdown-menu-demo',
  //   type: 'components:example',
  //   registryDependencies: ['dropdown-menu'],
  //   files: ['src/docs/components/example/dropdown-menu-demo.tsx'],
  // },
  // {
  //   name: 'dropdown-menu-checkboxes',
  //   type: 'components:example',
  //   registryDependencies: ['dropdown-menu', 'checkbox'],
  //   files: ['src/docs/components/example/dropdown-menu-checkboxes.tsx'],
  // },
  // {
  //   name: 'dropdown-menu-radio-group',
  //   type: 'components:example',
  //   registryDependencies: ['dropdown-menu', 'radio-group'],
  //   files: ['src/docs/components/example/dropdown-menu-radio-group.tsx'],
  // },
  // {
  //   name: 'hover-card-demo',
  //   type: 'components:example',
  //   registryDependencies: ['hover-card'],
  //   files: ['src/docs/components/example/hover-card-demo.tsx'],
  // },
  // {
  //   name: 'input-demo',
  //   type: 'components:example',
  //   registryDependencies: ['input'],
  //   files: ['src/docs/components/example/input-demo.tsx'],
  // },
  // {
  //   name: 'input-disabled',
  //   type: 'components:example',
  //   registryDependencies: ['input'],
  //   files: ['src/docs/components/example/input-disabled.tsx'],
  // },
  // {
  //   name: 'input-file',
  //   type: 'components:example',
  //   registryDependencies: ['input'],
  //   files: ['src/docs/components/example/input-file.tsx'],
  // },
  // {
  //   name: 'input-form',
  //   type: 'components:example',
  //   registryDependencies: ['input', 'button', 'form'],
  //   files: ['src/docs/components/example/input-form.tsx'],
  // },
  // {
  //   name: 'input-with-button',
  //   type: 'components:example',
  //   registryDependencies: ['input', 'button'],
  //   files: ['src/docs/components/example/input-with-button.tsx'],
  // },
  // {
  //   name: 'input-with-label',
  //   type: 'components:example',
  //   registryDependencies: ['input', 'button', 'label'],
  //   files: ['src/docs/components/example/input-with-label.tsx'],
  // },
  // {
  //   name: 'input-with-text',
  //   type: 'components:example',
  //   registryDependencies: ['input', 'button', 'label'],
  //   files: ['src/docs/components/example/input-with-text.tsx'],
  // },
  // {
  //   name: 'label-demo',
  //   type: 'components:example',
  //   registryDependencies: ['label'],
  //   files: ['src/docs/components/example/label-demo.tsx'],
  // },
  // {
  //   name: 'menubar-demo',
  //   type: 'components:example',
  //   registryDependencies: ['menubar'],
  //   files: ['src/docs/components/example/menubar-demo.tsx'],
  // },
  // {
  //   name: 'navigation-menu-demo',
  //   type: 'components:example',
  //   registryDependencies: ['navigation-menu'],
  //   files: ['src/docs/components/example/navigation-menu-demo.tsx'],
  // },
  // {
  //   name: 'pagination-demo',
  //   type: 'components:example',
  //   registryDependencies: ['pagination'],
  //   files: ['src/docs/components/example/pagination-demo.tsx'],
  // },
  // {
  //   name: 'popover-demo',
  //   type: 'components:example',
  //   registryDependencies: ['popover'],
  //   files: ['src/docs/components/example/popover-demo.tsx'],
  // },
  // {
  //   name: 'progress-demo',
  //   type: 'components:example',
  //   registryDependencies: ['progress'],
  //   files: ['src/docs/components/example/progress-demo.tsx'],
  // },
  // {
  //   name: 'radio-group-demo',
  //   type: 'components:example',
  //   registryDependencies: ['radio-group'],
  //   files: ['src/docs/components/example/radio-group-demo.tsx'],
  // },
  // {
  //   name: 'radio-group-form',
  //   type: 'components:example',
  //   registryDependencies: ['radio-group', 'form'],
  //   files: ['src/docs/components/example/radio-group-form.tsx'],
  // },
  // {
  //   name: 'resizable-demo',
  //   type: 'components:example',
  //   registryDependencies: ['resizable'],
  //   files: ['src/docs/components/example/resizable-demo.tsx'],
  // },
  // {
  //   name: 'resizable-demo-with-handle',
  //   type: 'components:example',
  //   registryDependencies: ['resizable'],
  //   files: ['src/docs/components/example/resizable-demo-with-handle.tsx'],
  // },
  // {
  //   name: 'resizable-vertical',
  //   type: 'components:example',
  //   registryDependencies: ['resizable'],
  //   files: ['src/docs/components/example/resizable-vertical.tsx'],
  // },
  // {
  //   name: 'resizable-handle',
  //   type: 'components:example',
  //   registryDependencies: ['resizable'],
  //   files: ['src/docs/components/example/resizable-handle.tsx'],
  // },
  // {
  //   name: 'scroll-area-demo',
  //   type: 'components:example',
  //   registryDependencies: ['scroll-area'],
  //   files: ['src/docs/components/example/scroll-area-demo.tsx'],
  // },
  // {
  //   name: 'scroll-area-horizontal-demo',
  //   type: 'components:example',
  //   registryDependencies: ['scroll-area'],
  //   files: ['src/docs/components/example/scroll-area-horizontal-demo.tsx'],
  // },
  // {
  //   name: 'select-demo',
  //   type: 'components:example',
  //   registryDependencies: ['select'],
  //   files: ['src/docs/components/example/select-demo.tsx'],
  // },
  // {
  //   name: 'select-scrollable',
  //   type: 'components:example',
  //   registryDependencies: ['select'],
  //   files: ['src/docs/components/example/select-scrollable.tsx'],
  // },
  // {
  //   name: 'select-form',
  //   type: 'components:example',
  //   registryDependencies: ['select'],
  //   files: ['src/docs/components/example/select-form.tsx'],
  // },
  // {
  //   name: 'separator-demo',
  //   type: 'components:example',
  //   registryDependencies: ['separator'],
  //   files: ['src/docs/components/example/separator-demo.tsx'],
  // },
  // {
  //   name: 'sheet-demo',
  //   type: 'components:example',
  //   registryDependencies: ['sheet'],
  //   files: ['src/docs/components/example/sheet-demo.tsx'],
  // },
  // {
  //   name: 'sheet-side',
  //   type: 'components:example',
  //   registryDependencies: ['sheet'],
  //   files: ['src/docs/components/example/sheet-side.tsx'],
  // },
  // {
  //   name: 'skeleton-demo',
  //   type: 'components:example',
  //   registryDependencies: ['skeleton'],
  //   files: ['src/docs/components/example/skeleton-demo.tsx'],
  // },
  // {
  //   name: 'skeleton-card',
  //   type: 'components:example',
  //   registryDependencies: ['skeleton'],
  //   files: ['src/docs/components/example/skeleton-card.tsx'],
  // },
  // {
  //   name: 'slider-demo',
  //   type: 'components:example',
  //   registryDependencies: ['slider'],
  //   files: ['src/docs/components/example/slider-demo.tsx'],
  // },
  // {
  //   name: 'sonner-demo',
  //   type: 'components:example',
  //   registryDependencies: ['sonner'],
  //   files: ['src/docs/components/example/sonner-demo.tsx'],
  // },
  // {
  //   name: 'switch-demo',
  //   type: 'components:example',
  //   registryDependencies: ['switch'],
  //   files: ['src/docs/components/example/switch-demo.tsx'],
  // },
  // {
  //   name: 'switch-form',
  //   type: 'components:example',
  //   registryDependencies: ['switch', 'form'],
  //   files: ['src/docs/components/example/switch-form.tsx'],
  // },
  // {
  //   name: 'table-demo',
  //   type: 'components:example',
  //   registryDependencies: ['table'],
  //   files: ['src/docs/components/example/table-demo.tsx'],
  // },
  // {
  //   name: 'tabs-demo',
  //   type: 'components:example',
  //   registryDependencies: ['tabs'],
  //   files: ['src/docs/components/example/tabs-demo.tsx'],
  // },
  // {
  //   name: 'textarea-demo',
  //   type: 'components:example',
  //   registryDependencies: ['textarea'],
  //   files: ['src/docs/components/example/textarea-demo.tsx'],
  // },
  // {
  //   name: 'textarea-disabled',
  //   type: 'components:example',
  //   registryDependencies: ['textarea'],
  //   files: ['src/docs/components/example/textarea-disabled.tsx'],
  // },
  // {
  //   name: 'textarea-form',
  //   type: 'components:example',
  //   registryDependencies: ['textarea', 'form'],
  //   files: ['src/docs/components/example/textarea-form.tsx'],
  // },
  // {
  //   name: 'textarea-with-button',
  //   type: 'components:example',
  //   registryDependencies: ['textarea', 'button'],
  //   files: ['src/docs/components/example/textarea-with-button.tsx'],
  // },
  // {
  //   name: 'textarea-with-label',
  //   type: 'components:example',
  //   registryDependencies: ['textarea', 'label'],
  //   files: ['src/docs/components/example/textarea-with-label.tsx'],
  // },
  // {
  //   name: 'textarea-with-text',
  //   type: 'components:example',
  //   registryDependencies: ['textarea', 'label'],
  //   files: ['src/docs/components/example/textarea-with-text.tsx'],
  // },
  // {
  //   name: 'toast-demo',
  //   type: 'components:example',
  //   registryDependencies: ['toast'],
  //   files: ['src/docs/components/example/toast-demo.tsx'],
  // },
  // {
  //   name: 'toast-destructive',
  //   type: 'components:example',
  //   registryDependencies: ['toast'],
  //   files: ['src/docs/components/example/toast-destructive.tsx'],
  // },
  // {
  //   name: 'toast-simple',
  //   type: 'components:example',
  //   registryDependencies: ['toast'],
  //   files: ['src/docs/components/example/toast-simple.tsx'],
  // },
  // {
  //   name: 'toast-with-action',
  //   type: 'components:example',
  //   registryDependencies: ['toast'],
  //   files: ['src/docs/components/example/toast-with-action.tsx'],
  // },
  // {
  //   name: 'toast-with-title',
  //   type: 'components:example',
  //   registryDependencies: ['toast'],
  //   files: ['src/docs/components/example/toast-with-title.tsx'],
  // },
  // {
  //   name: 'toggle-group-demo',
  //   type: 'components:example',
  //   registryDependencies: ['toggle-group'],
  //   files: ['src/docs/components/example/toggle-group-demo.tsx'],
  // },
  // {
  //   name: 'toggle-group-disabled',
  //   type: 'components:example',
  //   registryDependencies: ['toggle-group'],
  //   files: ['src/docs/components/example/toggle-group-disabled.tsx'],
  // },
  // {
  //   name: 'toggle-group-lg',
  //   type: 'components:example',
  //   registryDependencies: ['toggle-group'],
  //   files: ['src/docs/components/example/toggle-group-lg.tsx'],
  // },
  // {
  //   name: 'toggle-group-outline',
  //   type: 'components:example',
  //   registryDependencies: ['toggle-group'],
  //   files: ['src/docs/components/example/toggle-group-outline.tsx'],
  // },
  // {
  //   name: 'toggle-group-sm',
  //   type: 'components:example',
  //   registryDependencies: ['toggle-group'],
  //   files: ['src/docs/components/example/toggle-group-sm.tsx'],
  // },
  // {
  //   name: 'toggle-group-single',
  //   type: 'components:example',
  //   registryDependencies: ['toggle-group'],
  //   files: ['src/docs/components/example/toggle-group-single.tsx'],
  // },
  // {
  //   name: 'toggle-demo',
  //   type: 'components:example',
  //   registryDependencies: ['toggle'],
  //   files: ['src/docs/components/example/toggle-demo.tsx'],
  // },
  // {
  //   name: 'toggle-disabled',
  //   type: 'components:example',
  //   registryDependencies: ['toggle'],
  //   files: ['src/docs/components/example/toggle-disabled.tsx'],
  // },
  // {
  //   name: 'toggle-lg',
  //   type: 'components:example',
  //   registryDependencies: ['toggle'],
  //   files: ['src/docs/components/example/toggle-lg.tsx'],
  // },
  // {
  //   name: 'toggle-outline',
  //   type: 'components:example',
  //   registryDependencies: ['toggle'],
  //   files: ['src/docs/components/example/toggle-outline.tsx'],
  // },
  // {
  //   name: 'toggle-sm',
  //   type: 'components:example',
  //   registryDependencies: ['toggle'],
  //   files: ['src/docs/components/example/toggle-sm.tsx'],
  // },
  // {
  //   name: 'toggle-with-text',
  //   type: 'components:example',
  //   registryDependencies: ['toggle'],
  //   files: ['src/docs/components/example/toggle-with-text.tsx'],
  // },
  // {
  //   name: 'tooltip-demo',
  //   type: 'components:example',
  //   registryDependencies: ['tooltip'],
  //   files: ['src/docs/components/example/tooltip-demo.tsx'],
  // },
]

export const registry: Registry = [...example]
