// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "accordion-demo": {
    name: "accordion-demo",
    type: "components:example",
    egistryDependencies: ["accordion"],
    component: React.lazy(() => import("@/docs/components/example/accordion-demo")),
    files: ["src/docs/components/example/accordion-demo.tsx"],
  }, "alert-demo": {
    name: "alert-demo",
    type: "components:example",
    egistryDependencies: ["alert"],
    component: React.lazy(() => import("@/docs/components/example/alert-demo")),
    files: ["src/docs/components/example/alert-demo.tsx"],
  }, "alert-destructive": {
    name: "alert-destructive",
    type: "components:example",
    egistryDependencies: ["alert"],
    component: React.lazy(() => import("@/docs/components/example/alert-destructive")),
    files: ["src/docs/components/example/alert-destructive.tsx"],
  }, "alert-dialog-demo": {
    name: "alert-dialog-demo",
    type: "components:example",
    egistryDependencies: ["alert-dialog", "button"],
    component: React.lazy(() => import("@/docs/components/example/alert-dialog-demo")),
    files: ["src/docs/components/example/alert-dialog-demo.tsx"],
  }, "avatar-demo": {
    name: "avatar-demo",
    type: "components:example",
    egistryDependencies: ["avatar"],
    component: React.lazy(() => import("@/docs/components/example/avatar-demo")),
    files: ["src/docs/components/example/avatar-demo.tsx"],
  }, "badge-demo": {
    name: "badge-demo",
    type: "components:example",
    egistryDependencies: ["badge"],
    component: React.lazy(() => import("@/docs/components/example/badge-demo")),
    files: ["src/docs/components/example/badge-demo.tsx"],
  }, "badge-destructive": {
    name: "badge-destructive",
    type: "components:example",
    egistryDependencies: ["badge"],
    component: React.lazy(() => import("@/docs/components/example/badge-destructive")),
    files: ["src/docs/components/example/badge-destructive.tsx"],
  }, "badge-outline": {
    name: "badge-outline",
    type: "components:example",
    egistryDependencies: ["badge"],
    component: React.lazy(() => import("@/docs/components/example/badge-outline")),
    files: ["src/docs/components/example/badge-outline.tsx"],
  }, "badge-secondary": {
    name: "badge-secondary",
    type: "components:example",
    egistryDependencies: ["badge"],
    component: React.lazy(() => import("@/docs/components/example/badge-secondary")),
    files: ["src/docs/components/example/badge-secondary.tsx"],
  }, "button-demo": {
    name: "button-demo",
    type: "components:example",
    egistryDependencies: ["button"],
    component: React.lazy(() => import("@/docs/components/example/button-demo")),
    files: ["src/docs/components/example/button-demo.tsx"],
  },
}
